### ISSUE TITLE
Inference on custom input

### ISSUE THREAD

**Issue by danielcrane** [jytime/DICL-Flow#2]
First of all, thanks for sharing your work, I look forward to trying it.

I was wondering if you could possibly provide in the `README.md` an example of how to run inference with a user-defined input?

Thanks!

**Comment by jytime** [comment]
Hi Daniel,

I will make some examples later. Specifically, you can easily build a custom dataset based on the class ```FlowDataset``` in datasets.py, just like the classes ```MpiSintel``` or ```FlyingChairs```.  It requires ```self.flow_list``` and ```self.image_list```, i.e., the address to load the image pair and optical flow.  If you do not have ground truth optical flow, just modify this line https://github.com/jytime/DICL-Flow/blob/ac88ff0a7ea52641c17ddfd3cd0846ed53559904/datasets.py#L65, such as setting all the flow to be zeros.

Best,
Jianyuan

**Comment by danielcrane** [comment]
@jytime Thanks for the fast response, I'll give it a try!
