### ISSUE TITLE
Flow Rotation for data augmentation

### ISSUE THREAD

**Issue by MeowZheng** [jytime/DICL-Flow#3]
Hi,

Many thanks for sharing your nice work. I have a question about [`class RandomRotate`](https://github.com/jytime/DICL-Flow/blob/main/flow_transforms.py#L290), is this supposed to be like `target[:,:,1] = np.sin(angle1_rad)*target_[:,:,0]  -np.cos(angle1_rad)*target_[:,:,1]`?

thanks again!
Miao

**Comment by jytime** [comment]
Hi Miao,

Though we did not use RandomRotate() in our final implementation, I think I tested and visualized it in the early stage. It should be right. You could also visualize some examples using RandomRotate() and this may be the simplest way to check its correctness.

By the way, according to my experience, RandomRotate() will bring some occ areas in image corners, which may not be a good choice for augmentation.

Best,
Jianyuan
