### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hmorimitsu** [jytime/DICL-Flow#4]
Hi, thank you for sharing the code for this very interesting work!

I am developing an open source unified platform with several optical flow methods (you can see it here: https://github.com/hmorimitsu/ptlflow) and I would love to add DICL-Flow as well. However, I could not find a license for your code, so I do not know if I am allowed to add this code or not.

Therefore, I just would like to ask if you had any plans of adding a license to this code just to let others know how it can be used.

Best regards,

Henrique

**Comment by jytime** [comment]
Hi Henrique,

Thanks for your interest. Sure, please feel free to add this to your repository. We follow the MIT license.

Best,
Jianyuan

**Comment by hmorimitsu** [comment]
Thank you for the quick reply.

I have added DICL-Flow to PTLFlow now.
