### ISSUE TITLE
PWCNet + DICL

### ISSUE THREAD

**Issue by YogaLai** [jytime/DICL-Flow#5]
First of all, thanks for sharing your excellent work.
I want to reproduce PWCNet + DICL. And I have a question about PWCNet + DICL.

Doest it use PWCNet feature extraction to build DICL cost and use matching net module to learn the cost, then use PWCNet optical flow estimator CNN to progress this cost to generate optical flow?

Thanks

**Comment by jytime** [comment]
Hi,

Yes, the overall process is like this. Please notice that the learning rate should be reduced to half of the value used by the original PWCNet to keep the learning stable (if I remember this correctly).
